<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxqnqb2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxqnqb2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOxqnqb2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOxqnqb2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOxqnqb2\appProdProjectContainer([
    'container.build_hash' => 'Oxqnqb2',
    'container.build_id' => '75cb5907',
    'container.build_time' => 1581017778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxqnqb2');
