<?php

namespace ElitBundle\Repository;

/**
 * applicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class applicationRepository extends \Doctrine\ORM\EntityRepository
{
}
