<?php

namespace ElitBundle\Repository;

/**
 * CategorybookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorybookRepository extends \Doctrine\ORM\EntityRepository
{
}
