<?php

namespace ElitBundle\Repository;

/**
 * complaintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class complaintsRepository extends \Doctrine\ORM\EntityRepository
{
}
