<?php

namespace ElitBundle\Repository;

/**
 * rendezvousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rendezvousRepository extends \Doctrine\ORM\EntityRepository
{
}
