<?php

namespace ElitBundle\Repository;

/**
 * SchoolmeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolmeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
