application_index:
    path:     /
    defaults: { _controller: "ElitBundle:application:index" }
    methods:  GET

application_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:application:show" }
    methods:  GET

application_new:
    path:     /new
    defaults: { _controller: "ElitBundle:application:new" }
    methods:  [GET, POST]

application_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:application:edit" }
    methods:  [GET, POST]

application_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:application:delete" }
    methods:  DELETE
application_stat:
    path:     /stat
    defaults: { _controller: "ElitBundle:application:stat" }
    methods:  GET