book_index:
    path:     /
    defaults: { _controller: "ElitBundle:book:index" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "ElitBundle:book:new" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:book:edit" }
    methods:  [GET, POST]

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:book:delete" }
    methods:  DELETE

book_showbook:
    path:     /showbook
    defaults: { _controller: "ElitBundle:book:showbook" }
    methods:  GET

book_showbookfront:
    path:     /{id}/showfront
    defaults: { _controller: "ElitBundle:book:showbookfront" }
    methods:  GET
book_stat:
    path:     /stat
    defaults: { _controller: "ElitBundle:book:stat" }
    methods:  GET