categorybook_index:
    path:     /
    defaults: { _controller: "ElitBundle:CategoryBook:index" }
    methods:  GET

categorybook_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:CategoryBook:show" }
    methods:  GET

categorybook_new:
    path:     /new
    defaults: { _controller: "ElitBundle:CategoryBook:new" }
    methods:  [GET, POST]

categorybook_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:CategoryBook:edit" }
    methods:  [GET, POST]

categorybook_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:CategoryBook:delete" }
    methods:  DELETE
