complaints_index:
    path:     /
    defaults: { _controller: "ElitBundle:complaints:index" }
    methods:  GET

complaints_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:complaints:show" }
    methods:  GET

complaints_new:
    path:     /new
    defaults: { _controller: "ElitBundle:complaints:new" }
    methods:  [GET, POST]

complaints_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:complaints:edit" }
    methods:  [GET, POST]

complaints_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:complaints:delete" }
    methods:  DELETE
