event_index:
    path:     /
    defaults: { _controller: "ElitBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "ElitBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:Event:delete" }
    methods:  DELETE
event_calendar:
    path:     /calendar
    defaults: { _controller: "ElitBundle:Event:calendar" }

event_del:
    path:     /del/{id}
    defaults: { _controller: "ElitBundle:Event:del" }


event_pdf:
  path:     /pdf
  defaults: { _controller: "ElitBundle:Event:pdf" }