<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrw0nql\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrw0nql/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWrw0nql.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWrw0nql\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWrw0nql\appDevDebugProjectContainer([
    'container.build_hash' => 'Wrw0nql',
    'container.build_id' => '0eb3abe2',
    'container.build_time' => 1581178301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrw0nql');
