<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerX6y5x8h\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX6y5x8h/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX6y5x8h.legacy');
=======
if (\class_exists(\ContainerT3nge86\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3nge86/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT3nge86.legacy');
>>>>>>> parent of a07ca40b... appointement/application crud and template integration changes

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerX6y5x8h\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX6y5x8h\appDevDebugProjectContainer([
    'container.build_hash' => 'X6y5x8h',
    'container.build_id' => '4dad533e',
    'container.build_time' => 1581468517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX6y5x8h');
=======
    \class_alias(\ContainerT3nge86\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerT3nge86\appDevDebugProjectContainer([
    'container.build_hash' => 'T3nge86',
    'container.build_id' => '4fb16fab',
    'container.build_time' => 1581628511,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3nge86');
>>>>>>> parent of a07ca40b... appointement/application crud and template integration changes
