<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0gmkzv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0gmkzv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0gmkzv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0gmkzv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX0gmkzv\appDevDebugProjectContainer([
    'container.build_hash' => 'X0gmkzv',
    'container.build_id' => '2744c04c',
    'container.build_time' => 1581767627,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0gmkzv');
